version: '3.4'

services:
  nutcache.webui:
    image: ${DOCKER_REGISTRY-}nutcachewebui
    build:
      context: .
      dockerfile: src/Nutcache.WebUI/Dockerfile


  nutcache.webapi:
    image: ${DOCKER_REGISTRY-}nutcachewebapi
    build:
      context: .
      dockerfile: src/Nutcache.WebApi/Dockerfile

